import type { SerialPublicationArchiveSelect } from '../../db/types/serial/types-serial-publication-archive.ts';

export function asSerialPublicationArchiveAdminRead(e: SerialPublicationArchiveSelect): SerialPublicationArchiveSelect {
  const {
    id,
    serial_publication_id,
    title,
    subtitle,
    place_of_publication,
    printer,
    issued_from_year,
    issued_from_number,
    frequency,
    frequency_other,
    language,
    publication_type,
    publication_type_other,
    medium,
    medium_other,
    url,
    previous,
    main_series,
    subseries,
    another_medium,
    additional_info,
    created,
    created_by,
  } = e;

  return {
    id,
    serial_publication_id,
    title,
    subtitle,
    place_of_publication,
    printer,
    issued_from_year,
    issued_from_number,
    frequency,
    frequency_other,
    language,
    publication_type,
    publication_type_other,
    medium,
    medium_other,
    url,
    previous,
    main_series,
    subseries,
    another_medium,
    additional_info,
    created,
    created_by,
  };
}
