openapi: '3.1.0'

info:
  version: 2.0.0
  title: Identifier Services API v2
  contact:
    name: Identifier Services support
    url: https://www.kansalliskirjasto.fi/fi/palvelut/isbn-tunnus
tags:
  - name: monograph
    description: Monograph publication and related identifier management
  - name: isbn
    description: ISBN identifier management

paths:
  /v2/health:
    $ref: './resources/health/root.yaml'

  /v2/monograph/isbn-ranges:
    $ref: './resources/monograph/isbn-ranges/root.yaml'
  /v2/monograph/isbn-ranges/{id}:
    $ref: './resources/monograph/isbn-ranges/id.yaml'

  /v2/monograph/isbn-publisher-ranges:
    $ref: './resources/monograph/isbn-publisher-ranges/root.yaml'
  /v2/monograph/isbn-publisher-ranges/{id}:
    $ref: './resources/monograph/isbn-publisher-ranges/id.yaml'

  /v2/monograph/publishers/{id}:
    $ref: './resources/monograph/publishers/id.yaml'
  /v2/monograph/publishers/search:
    $ref: './resources/monograph/publishers/search.yaml'

  /v2/monograph/publications/{id}:
    $ref: './resources/monograph/publications/id.yaml'

  /v2/monograph/publication-expressions/{id}:
    $ref: './resources/monograph/publication-expressions/id.yaml'

  /v2/monograph/publication-manifestations/{id}:
    $ref: './resources/monograph/publication-manifestations/id.yaml'

  /v2/monograph/publication-requests:
    $ref: './resources/monograph/publication-requests/root.yaml'
  /v2/monograph/publication-requests/{id}:
    $ref: './resources/monograph/publication-requests/id.yaml'
  /v2/monograph/publication-requests/{id}/approve:
    $ref: './resources/monograph/publication-requests/approve.yaml'
  /v2/monograph/publication-requests/{id}/reject:
    $ref: './resources/monograph/publication-requests/reject.yaml'
  /v2/monograph/publication-requests/{id}/reprocess:
    $ref: './resources/monograph/publication-requests/reprocess.yaml'

components:
  securitySchemes:
    openId:
      type: openIdConnect
