openapi: '3.1.0'

info:
  version: 2.0.0
  title: Identifier Services API v2
  contact:
    name: Identifier Services support
    url: https://www.kansalliskirjasto.fi/fi/palvelut/isbn-tunnus
tags:
  - name: monograph
    description: Monograph publication and related identifier management
  - name: isbn
    description: ISBN identifier management

paths:
  /v2/health:
    $ref: './resources/health/root.yaml'

  /v2/monograph/isbn-ranges:
    $ref: './resources/monograph/isbn-ranges/root.yaml'
  /v2/monograph/isbn-ranges/{id}:
    $ref: './resources/monograph/isbn-ranges/id.yaml'

  /v2/monograph/monograph-publishers:
    $ref: './resources/monograph/monograph-publishers/root.yaml'
  /v2/monograph/monograph-publishers/{id}:
    $ref: './resources/monograph/monograph-publishers/id.yaml'

components:
  securitySchemes:
    openId:
      type: openIdConnect
