-- serial publication archive v2.0.0-alpha.2
CREATE TABLE serial_publication_archive (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  serial_publication_id INT UNSIGNED NOT NULL,
  title VARCHAR(200) NOT NULL,
  subtitle VARCHAR(200),
  place_of_publication VARCHAR(100),
  printer VARCHAR(100),
  issued_from_year VARCHAR(4),
  issued_from_number VARCHAR(100),
  frequency CHAR(1),
  frequency_other VARCHAR(50),
  `language` VARCHAR(50),
  publication_type VARCHAR(25),
  publication_type_other VARCHAR(50),
  medium VARCHAR(7),
  medium_other VARCHAR(50),
  `url` VARCHAR(100),
  previous JSON NOT NULL,
  main_series JSON NOT NULL,
  subseries JSON NOT NULL,
  another_medium JSON NOT NULL,
  additional_info VARCHAR(2000),
  created DATETIME NOT NULL,
  created_by VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (serial_publication_id) REFERENCES serial_publication(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE utf8mb4_swedish_ci;