-- Monograph publication request v2.0.0-alpha.1
CREATE TABLE monograph_publication_request (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  monograph_publisher_id INT UNSIGNED,
  monograph_publication_id INT UNSIGNED NOT NULL,
  official_name VARCHAR(100) NOT NULL,
  publisher_identifier_str VARCHAR(20),
  `address` VARCHAR(100),
  zip VARCHAR(10),
  city VARCHAR(50),
  phone VARCHAR(30),
  email VARCHAR(100),
  lang_code VARCHAR(5) NOT NULL,
  contact_person VARCHAR(100),
  published_before BOOLEAN NOT NULL,
  publishing_activity VARCHAR(10),
  publishing_activity_amount VARCHAR(5),
  publications_intra BOOLEAN NOT NULL,
  publications_public BOOLEAN NOT NULL,
  comments VARCHAR(2000),
  on_process BOOLEAN NOT NULL,
  created DATETIME NOT NULL,
  created_by VARCHAR(36) NOT NULL,
  modified DATETIME NOT NULL,
  modified_by VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (monograph_publisher_id) REFERENCES monograph_publisher(id),
  FOREIGN KEY (monograph_publication_id) REFERENCES monograph_publication(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE utf8mb4_swedish_ci;